### ISSUE TITLE
Adding to Documentation

### ISSUE THREAD

**Issue by Diana1407** [Pepi100/Tales-of-Quarto#13]

**Comment by Diana1407** [comment]
**Functional Decomposition**

- User Interface (UI)
  -   Main Menu - here you can choose the saving slot, start the game, quit the game
  -   Inventory and Crafting GUI - here you can see what the player has in the inventory, how many pieces of materials. Also you will be able to craft here based on some recipes and the stuff you have in the inventory.
  -   Option and Settings - here you can change the volume, resolution, display and the quality of graphics. You can also go back to the game and you can save the game.
  -   Pause Menu - here you can enter if you press ESC and you can go back to the main menu or to the settings menu

- The player
  - Movement - the player can move using the letters WASD
  - Mining and Resource Gathering - the player can hit the stones to mine, receive materials and collect them from the world
  - Combat - the player will be able to fight with some monsters in the world
  - Inventory system - the player will have some slots available for him to store some items. Also there will be some chests in the world where the player can let some items when his inventory is full.

- NPCs
  - Dialogue - the NPCs will provide a short dialogue for the player
  - Movement - they will have some animations 

- Biomes and Ecosystems
  - Different Biomes - the map will provide different regions such as: forests, deserts, oceans
  - Flora - while exploring the map the player can discovers different types of plants

- Gameplay Mechanics
  - Health - the player will have a health system that will modify when the player is in combat
  - Achievements - during the game the player will earn different achievements

- Sound and Music
  - Sound Effects - the game will have different sound effects depending on what the character does
  - Background Music - the game will have a permanent music playing

**Comment by DavidPatranjel** [comment]
Product statement
Tales of Quarto is an immersive 2D sandbox adventure game that invites curious players to embark on a journey as Quarto, a brave adventurer. Set in a captivating world, players will explore, mine resources, craft tools and weapons, and engage in battles against enemies. The ultimate quest is to rescue the kidnapped princess by confronting and defeating the menacing dragon. With dynamic gameplay and a vibrant pixel-art aesthetic, Tales of Quarto promises an engaging experience for adventurous and creative players.

**Comment by DavidPatranjel** [comment]
* de adaugat winning the game si game over la FD

**Comment by DavidPatranjel** [comment]
Sprint 1 + Acceptance criteria:

- As a player, I want to be able to put the game on pause, so that I can take a break.
  Scenario: Player pauses the game
  Given the game is running
  When the player selects the pause option
  Then the game should freeze and all in-game activities should cease
- As a player, I can see my inventory, so that I can craft the elements I need.
  Scenario: Player views inventory
  Given the player is in the game
  When the player accesses the inventory by pressing the 'E' key
  Then the player should see a list of items in their possession
- As a player, I want to have a menu where I can see the settings, so that I can access everything easily.
  Scenario: Player accesses the settings menu
  Given the player is in the game
  When the player opens the menu and selects settings
  Then the player should see options for all game settings
- As a player, I want to be able to explore around the world, so that I can have a better understanding of the surroundings and what I can use and do.
  Scenario: Player explores the game world
  Given the player is in the game
  When the player moves to different locations with WASD keys
  Then the player should move and encounter varied environments
- As a player, I want to be able to organize my inventory, so that I can use it more efficiently.
  Scenario: Player organizes inventory
  Given the player is in the game and has items in their inventory
  When the player rearranges items in the inventory by drag-and-drop
  Then the items should be reorganized 
- As a player, I want to be able to change the screen resolution, so that it will fit the user system.
  Scenario: Player changes screen resolution
  Given the player is in the game
  When the player goes to settings and adjusts the screen resolution
  Then the game window should resize accordingly to fit the user's system
- As a player, I want to be able to check the achievements I received, so that I can track my progress.
  Scenario: Player checks achievements
  Given the player is in the main menu interface
  When the player navigates to the achievements section
  Then the player should see a list of all earned achievements

**Comment by DavidPatranjel** [comment]
NFRs

Performance and Graphics Quality:
The game should have low-latency responsiveness, ensuring smooth gameplay on a variety of hardware configurations.
Load times for different game elements, such as worlds and textures, should be optimized for quick and efficient rendering.

Compatibility:
Tales of Quarto should be compatible with a broad range of devices that run on the Windows operating System.

User Interface (UI) Design:
The user interface should be intuitive and user-friendly, accommodating players of various experience levels.
Accessibility features, such as customizable display or music level, should be implemented for players with different needs.

Reliability:
The game should have a stable architecture, minimizing crashes, bugs, and other disruptions to provide a reliable gaming experience.

Resource Efficiency:
The game should be designed to use system resources efficiently, minimizing CPU and GPU usage to extend battery life for players on laptops and other mobile devices.

**Comment by Diana1407** [comment]
![User Journey Map](https://github.com/Pepi100/Tales-of-Quarto/assets/93083024/4df346a2-6c74-46dd-824a-50a4c7fdc0fb)
