### ISSUE TITLE
Userstories and UML Diagram

### ISSUE THREAD

**Issue by DavidPatranjel** [Pepi100/Tales-of-Quarto#2]
- [x] UML
- [x] Userstories

**Comment by DavidPatranjel** [comment]
Beta verion of uml
![UML T o Q](https://github.com/Pepi100/Tales-of-Quarto/assets/92601174/87b1cbb2-9b47-4053-a3b2-34ff73fd0ab6)

**Comment by Diana1407** [comment]
1. As a player, I can save my progress in the game, so that I can recover my play-state.
2. As a player, I want to be able to put the game on pause, so that I can take a break.
3. As a player, I can see my inventory, so that I can craft the elements I need.
4. As a player, I want to be able to organize my inventory, so that I can use it more efficiently. 
5. As  a player, I can put the music on mute, so that I can play in silence.
6. As a player, I want a simple and suggestive UI, so that I can easily use the game.
7. As a new player, I want to have access to the instructions of the game, so that I know how to play. 
8. As a player, I want to see an interesting storyline, so that I will be engaged.
9. As a player, I want to be able to change the volume of the game sound so that I can have a more immersive experience.
10. As a player, I want to have a menu where I can see the settings, so that I can access everything easily. 
11. As a player, I want to be able to change the screen resolution, so that it will fit the user system.
12. As a player, I want to be able to explore around the world, so that I can have a better understanding of the surroundings and what I can use and do.
13. As a player, I want to be able to fight enemies in the game, so that I will be more focused and attentive.
14. As a player, I want to be able to delete the saving slots, so that I can start over.
15. As a player, I want to be able to customize my character, so that I can have an immersive experience.
16. As a player, I want to be able to change the language, so that I can understand better.
17. As a player, I want to receive achievements, so that I know I did good.
18. As a player, I want to be able to check the achievements I received, so that I can track my progress.
19. As a player, I want to be able to see the crafting recipes, so that I can learn what I am able to craft.
20. As a player, I want to interact (destroy/ build) with the elements on the map, so that I can get materials.

**Comment by DavidPatranjel** [comment]
+de adaugat must/should/nice to have

**Comment by DavidPatranjel** [comment]
![UML ToQ](https://github.com/Pepi100/Tales-of-Quarto/assets/92601174/3395c09c-253d-493a-a7a3-59ec86197343)

**Comment by Diana1407** [comment]
Must Have
1. As a player, I can save my progress in the game, so that I can recover my play-state.
2. As a player, I want to be able to put the game on pause, so that I can take a break.
3. As a player, I can put the music on mute, so that I can play in silence.
4. As a player, I want a simple and suggestive UI, so that I can easily use the game.
5. As a player, I can see my inventory, so that I can craft the elements I need.
6. As a player, I want to have a menu where I can see the settings, so that I can access everything easily.
7. As a player, I want to interact (destroy/ build) with the elements on the map, so that I can get materials.
8. As a player, I want to be able to explore around the world, so that I can have a better understanding of the surroundings and what I can use and do.

Should Have
9. As a player, I want to be able to change the volume of the game sound, so that I can have a more immersive experience.
10. As a player, I want to be able to organize my inventory, so that I can use it more efficiently.
11. As a player, I want to be able to change the screen resolution, so that it will fit the user system.
12. As a player, I want to be able to fight enemies in the game, so that I will be more focused and attentive.
13. As a player, I want to be able to delete the saving slots, so that I can start over.
14. As a player, I want to receive achievements, so that I know I did good.
15. As a player, I want to be able to see the crafting recipes, so that I can learn what I am able to craft.

Nice To Have
16. As a player, I want to see an interesting storyline, so that I will be engaged.
17. As a new player, I want to have access to the instructions of the game, so that I know how to play.
18. As a player, I want to be able to customize my character, so that I can have an immersive experience.
19. As a player, I want to be able to change the language, so that I can understand better.
20. As a player, I want to be able to check the achievements I received, so that I can track my progress.

**Comment by DavidPatranjel** [comment]
La user story sa nu punem numerotare, ci punem bullet!!!
